[General]
sound = "assets/hyper-alarm.mp3"
poll = 100
custom_app_name = "pwalarmd notifier"
notify = true

[[Alarm]]
title = "Test alarm 1"
description = "Is this alarm working?"
time = 21:30:00
repeat = ["Su", "Sa", "Tu", "We", "Th", "Fr"]

[[Alarm]]
title = "Test alarm 2"
description = "A later alarm..."
time = 22:00:00
# By not listing repeat, this runs daily