[General]
sound = "assets/hyper-alarm.mp3"

[[Alarm]]
title = "Test alarm 1"
description = "Is this alarm working?"
time = 21:30:00
repeat = ["Su", "Sa", "Tu", "We", "Th", "Fr", "Sa"]

[[Alarm]]
title = "Test alarm 2"
description = "A later alarm..."
time = 22:00:00
repeatall = true
